version: '3'

networks:
  laravel:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: WebServer
    ports:
      -  "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php
    networks:
      - laravel
  mysql:
    image: mysql:5.7.39
    container_name: MySqlDatabase
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PHP
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel


